version: '3.7'

services:
  app:
    container_name: app-graduate
    build:
      context: .
      dockerfile: ./app/Dockerfile

    volumes:
      - type: bind
        source: ./app/
        target: /app/
        
      - type: bind
        source: ./app/tmp/sockets/
        target: /app/tmp/sockets/

      - type: bind
        source: ./static/
        target: /var/www/static/

      - type: bind
        source: ./mysql/data/
        target: /var/run/mysql/

      - type: bind
        source: ./mysql/sockets/
        target: /var/run/mysqld/

      - type: bind
        source: ./log/
        target: /var/www/log/

    environment:
      HOST: 'tks-r2021.f5.si'
      DBUG: 'False'
      RUN_MODE: 'compose'
      admin_password: 'adminpassword'

    restart: always

    depends_on:
      - nginx
      - db

  nginx:
    container_name: nginx-graduate
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

    ports:
      # - 8080:80
      - 8080:443

    volumes:
      - type: bind
        source: ./app/tmp/sockets/
        target: /app/tmp/sockets/

      - type: bind
        source: ./static/
        target: /static/

      - type: bind
        source: ./log/
        target: /var/www/log/

    restart: always

  db:
    container_name: mysql-graduate
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: django
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo

    volumes:
      - type: bind
        source: ./mysql/data/
        target: /var/lib/mysql/

      - type: bind
        source: ./mysql/sockets/
        target: /var/run/mysqld/


    restart: always
